export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';

//PROFILE
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
//buyer
export const GET_ADDRESS = 'GET_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS';
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_BILLING_ADDRESS = 'EDIT_BILLING_ADDRESS';
export const EDIT_SHIPPING_ADDRESS = 'EDIT_SHIPPING_ADDRESS';
export const UPDATE_BILLING_ADDRESS = 'UPDATE_BILLING_ADDRESS';
export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';
//seller
export const EDIT_LISTING = 'EDIT_LISTING';
export const DELETE_LISTING = 'DELETE_LISTING';
export const EDIT_PROFILE_PIC = 'EDIT_PROFILE_PIC';
export const GET_LISTING_DATA = 'GET_LISTING_DATA';

//SHOP LIST
export const MENU = 'MENU';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_LIKED_ITEMS = 'GET_LIKED_ITEMS';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const POST_ITEM = 'POST_ITEM';
export const POST_ERROR = 'POST_ERROR';
export const LIKE_ITEM = 'LIKE_ITEM';
export const LIKE_CART = 'LIKE_CART';
export const UNLIKE_ITEM = 'UNLIKE_ITEM';
export const LIKE_FAIL = 'LIKE_FAIL';
export const CART_ITEM = 'CART_ITEM';
export const UNCART_ITEM = 'UNCART_ITEM';
export const CART_FAIL = 'CART_FAIL';
export const PAY_START = 'PAY_START';
export const PAY_SUCCEED = 'PAY_SUCCEED';
export const PAY_FAIL = 'PAY_FAIL';

export const ADD_COMMENT = 'ADD_COMMENT';
